### ISSUE TITLE
使用SSM整合HttpClient，使用工具包设置DNS，打印出来的DNS为最新的，但是请求时调用的DNS为缓存的设置，QQ：385400188

### ISSUE THREAD

**Issue by luozhuwang** [alibaba/java-dns-cache-manipulator#45]

**Comment by mengsanjun** [comment]
这个问题应该是你使用的框架有自己的缓存，并非每次都去调用InetAddress的方法来解析域名。

**Comment by mengsanjun** [comment]
参考说明：
对于已经完成解析保存了IP的逻辑，设置JVM DNS缓存，不会生效！可以重新创建 连接或Client解决。
如对于HttpClient

https://github.com/alibaba/java-dns-cache-manipulator/tree/master/library#%E4%BD%BF%E7%94%A8%E6%B3%A8%E6%84%8F

**Comment by luozhuwang** [comment]
> 参考说明：
> 对于已经完成解析保存了IP的逻辑，设置JVM DNS缓存，不会生效！可以重新创建 连接或Client解决。
> 如对于HttpClient
> 
> https://github.com/alibaba/java-dns-cache-manipulator/tree/master/library#%E4%BD%BF%E7%94%A8%E6%B3%A8%E6%84%8F

嗯，用之前也看到了你这个篇幅，也不知道框架哪个地方先调用的缓存
DnsCache dnsCache = DnsCacheManipulator.getWholeDnsCache()
通过你这个代码，获取到最新的DNS，自己到时候仔细琢磨琢磨吧
