### ISSUE TITLE
how to share dns in all jvm process?

### ISSUE THREAD

**Issue by zzsoszz** [alibaba/java-dns-cache-manipulator#47]

**Comment by oldratlee** [comment]
I didn't find the solution for sharing `JVM dns cache`.

An optional solution is use the same config file for dns cache settings.
more info see documentation [通过`dns-cache.properties`文件批量配置](https://github.com/alibaba/java-dns-cache-manipulator/tree/master/library#%E9%80%9A%E8%BF%87dns-cacheproperties%E6%96%87%E4%BB%B6%E6%89%B9%E9%87%8F%E9%85%8D%E7%BD%AE)

-------------

没有找到『多个jvm进程共享一个dns』的方法。可以试试走`dns-cache.properties`文件配置文件。

能多说说你要需求场景吗？  @zzsoszz  :)
